# run:
#   timeout: 5m
#   modules-download-mode: readonly
# 
# linters:
#   disable-all: true
#   enable:
#     - errcheck
#     - gosimple
#     - govet
#     - ineffassign
#     - staticcheck
#     - typecheck
#     - unused
#     - gosec
#     - revive
#     - gocritic
#     - misspell
#     - goimports
#     - goconst
# 
# linters-settings:
#   govet:
#     check-shadowing: true
#   gofmt:
#     simplify: true
#   revive:
#     rules:
#       - name: exported
#         severity: warning
#       - name: package-comments
#         severity: warning
#   gosec:
#     excludes:
#       - G104 # We often handle errors explicitly, but sometimes ignore them in defer or simple writes where we don't care. Let's be strict but realistic.
#   gocritic:
#     enabled-tags:
#       - diagnostic
#       - experimental
#       - opinionated
#       - performance
#       - style
#     disabled-checks:
#       - whyNoLint
#       - wrapperFunc
# 
# issues:
#   exclude-use-default: false
#   max-issues-per-linter: 0
#   max-same-issues: 0
#   exclude-dirs:
#     - clay # Cgo binding, likely has generated-like code or C-isms
