package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

func main() {
	// Assume running from app directory (go run ./cmd/gen_node_actions.go)
	dir := "./nodes"

	// Parse the directory.
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("parse error: %v", err)
	}

	if len(pkgs) != 1 {
		// Might happen if there are test packages. Pick 'nodes'.
		if _, ok := pkgs["nodes"]; !ok {
			log.Fatalf("expected package 'nodes' in directory")
		}
	}

	pkg := pkgs["nodes"]

	var decls []string

	// Scan all files for `GEN:NodeAction` markers.
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			// Look for a "GEN:NodeAction" comment on or before the decl.
			if !hasGenTag(gen.Doc, "NodeAction") {
				continue
			}

			// Found one! Get the type name.
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				decls = append(decls, typeSpec.Name.Name)
			}
		}
	}
	slices.Sort(decls)

	// Generate code
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen_node_actions.go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "package nodes\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "import \"github.com/bvisness/flowshell/app/core\"\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "func init() {\n")
	for _, name := range decls {
		fmt.Fprintf(&b, "  core.RegisterNodeAction(%q, func() core.NodeAction { return &%s{} })\n", name, name)
	}
	fmt.Fprintf(&b, "}\n")
	fmt.Fprintf(&b, "\n")
	for _, name := range decls {
		fmt.Fprintf(&b, "func (a *%s) Tag() string {\n", name)
		fmt.Fprintf(&b, "  return %q\n", name)
		fmt.Fprintf(&b, "}\n")
	}

	// Format the generated source
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		// Print source if format fails
		fmt.Println(b.String())
		log.Fatalf("formatting failed: %v", err)
	}

	// Write to file inside nodes/
	filename := filepath.Join(dir, "node_actions_generated.go")
	if err := os.WriteFile(filename, src, 0o644); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("✅ Generated metadata for %d node actions\n", len(decls))
}

// Improved regex: matches // or /* followed by GEN:Tag
var reGenComment = regexp.MustCompile(`^\s*(?://|/\*)\s*GEN:([a-zA-Z0-9_,-]+)`)

func hasGenTag(doc *ast.CommentGroup, tag string) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		lines := strings.Split(c.Text, "\n")
		for _, line := range lines {
			if match := reGenComment.FindStringSubmatch(line); match != nil {
				tags := strings.Split(match[1], ",")
				if slices.Contains(tags, tag) {
					return true
				}
			}
		}
	}
	return false
}
