// Code generated by gen_node_actions.go; DO NOT EDIT.

package app

var allNodeActions = [...]NodeActionMeta{
	{Tag: "AddColumnAction", Alloc: func() NodeAction { return &AddColumnAction{} }},
	{Tag: "AggregateAction", Alloc: func() NodeAction { return &AggregateAction{} }},
	{Tag: "ConcatTablesAction", Alloc: func() NodeAction { return &ConcatTablesAction{} }},
	{Tag: "ConvertAction", Alloc: func() NodeAction { return &ConvertAction{} }},
	{Tag: "ExtractColumnAction", Alloc: func() NodeAction { return &ExtractColumnAction{} }},
	{Tag: "FilterEmptyAction", Alloc: func() NodeAction { return &FilterEmptyAction{} }},
	{Tag: "LinesAction", Alloc: func() NodeAction { return &LinesAction{} }},
	{Tag: "ListFilesAction", Alloc: func() NodeAction { return &ListFilesAction{} }},
	{Tag: "LoadFileAction", Alloc: func() NodeAction { return &LoadFileAction{} }},
	{Tag: "MinifyHTMLAction", Alloc: func() NodeAction { return &MinifyHTMLAction{} }},
	{Tag: "RunProcessAction", Alloc: func() NodeAction { return &RunProcessAction{} }},
	{Tag: "SaveFileAction", Alloc: func() NodeAction { return &SaveFileAction{} }},
	{Tag: "SelectColumnsAction", Alloc: func() NodeAction { return &SelectColumnsAction{} }},
	{Tag: "SortAction", Alloc: func() NodeAction { return &SortAction{} }},
	{Tag: "TransposeAction", Alloc: func() NodeAction { return &TransposeAction{} }},
	{Tag: "TrimSpacesAction", Alloc: func() NodeAction { return &TrimSpacesAction{} }},
	{Tag: "ValueAction", Alloc: func() NodeAction { return &ValueAction{} }},
}

func (a *AddColumnAction) Tag() string {
	return "AddColumnAction"
}

func (a *AggregateAction) Tag() string {
	return "AggregateAction"
}

func (a *ConcatTablesAction) Tag() string {
	return "ConcatTablesAction"
}

func (a *ConvertAction) Tag() string {
	return "ConvertAction"
}

func (a *ExtractColumnAction) Tag() string {
	return "ExtractColumnAction"
}

func (a *FilterEmptyAction) Tag() string {
	return "FilterEmptyAction"
}

func (a *LinesAction) Tag() string {
	return "LinesAction"
}

func (a *ListFilesAction) Tag() string {
	return "ListFilesAction"
}

func (a *LoadFileAction) Tag() string {
	return "LoadFileAction"
}

func (a *MinifyHTMLAction) Tag() string {
	return "MinifyHTMLAction"
}

func (a *RunProcessAction) Tag() string {
	return "RunProcessAction"
}

func (a *SaveFileAction) Tag() string {
	return "SaveFileAction"
}

func (a *SelectColumnsAction) Tag() string {
	return "SelectColumnsAction"
}

func (a *SortAction) Tag() string {
	return "SortAction"
}

func (a *TransposeAction) Tag() string {
	return "TransposeAction"
}

func (a *TrimSpacesAction) Tag() string {
	return "TrimSpacesAction"
}

func (a *ValueAction) Tag() string {
	return "ValueAction"
}
