// Code generated by gen_node_actions.go; DO NOT EDIT.

package nodes

import "github.com/bvisness/flowshell/app/core"

func init() {
	core.RegisterNodeAction("AddColumnAction", func() core.NodeAction { return &AddColumnAction{} })
	core.RegisterNodeAction("AggregateAction", func() core.NodeAction { return &AggregateAction{} })
	core.RegisterNodeAction("BarChartAction", func() core.NodeAction { return &BarChartAction{} })
	core.RegisterNodeAction("CaseConvertAction", func() core.NodeAction { return &CaseConvertAction{} })
	core.RegisterNodeAction("ConcatTablesAction", func() core.NodeAction { return &ConcatTablesAction{} })
	core.RegisterNodeAction("ConvertAction", func() core.NodeAction { return &ConvertAction{} })
	core.RegisterNodeAction("CopyFileAction", func() core.NodeAction { return &CopyFileAction{} })
	core.RegisterNodeAction("DeleteFileAction", func() core.NodeAction { return &DeleteFileAction{} })
	core.RegisterNodeAction("ExtractColumnAction", func() core.NodeAction { return &ExtractColumnAction{} })
	core.RegisterNodeAction("FilterEmptyAction", func() core.NodeAction { return &FilterEmptyAction{} })
	core.RegisterNodeAction("FormatStringAction", func() core.NodeAction { return &FormatStringAction{} })
	core.RegisterNodeAction("FormulaAction", func() core.NodeAction { return &FormulaAction{} })
	core.RegisterNodeAction("GateAction", func() core.NodeAction { return &GateAction{} })
	core.RegisterNodeAction("GetMousePositionAction", func() core.NodeAction { return &GetMousePositionAction{} })
	core.RegisterNodeAction("GetVariableAction", func() core.NodeAction { return &GetVariableAction{} })
	core.RegisterNodeAction("GraphInputAction", func() core.NodeAction { return &GraphInputAction{} })
	core.RegisterNodeAction("GraphOutputAction", func() core.NodeAction { return &GraphOutputAction{} })
	core.RegisterNodeAction("HTTPRequestAction", func() core.NodeAction { return &HTTPRequestAction{} })
	core.RegisterNodeAction("IfElseAction", func() core.NodeAction { return &IfElseAction{} })
	core.RegisterNodeAction("JoinTextAction", func() core.NodeAction { return &JoinTextAction{} })
	core.RegisterNodeAction("JsonQueryAction", func() core.NodeAction { return &JsonQueryAction{} })
	core.RegisterNodeAction("LineChartAction", func() core.NodeAction { return &LineChartAction{} })
	core.RegisterNodeAction("LinesAction", func() core.NodeAction { return &LinesAction{} })
	core.RegisterNodeAction("ListFilesAction", func() core.NodeAction { return &ListFilesAction{} })
	core.RegisterNodeAction("LoadFileAction", func() core.NodeAction { return &LoadFileAction{} })
	core.RegisterNodeAction("MakeDirAction", func() core.NodeAction { return &MakeDirAction{} })
	core.RegisterNodeAction("MapAction", func() core.NodeAction { return &MapAction{} })
	core.RegisterNodeAction("MergeAction", func() core.NodeAction { return &MergeAction{} })
	core.RegisterNodeAction("MinifyHTMLAction", func() core.NodeAction { return &MinifyHTMLAction{} })
	core.RegisterNodeAction("MoveFileAction", func() core.NodeAction { return &MoveFileAction{} })
	core.RegisterNodeAction("ParseTimeAction", func() core.NodeAction { return &ParseTimeAction{} })
	core.RegisterNodeAction("PromptUserAction", func() core.NodeAction { return &PromptUserAction{} })
	core.RegisterNodeAction("RegexFindAllAction", func() core.NodeAction { return &RegexFindAllAction{} })
	core.RegisterNodeAction("RegexMatchAction", func() core.NodeAction { return &RegexMatchAction{} })
	core.RegisterNodeAction("RegexReplaceAction", func() core.NodeAction { return &RegexReplaceAction{} })
	core.RegisterNodeAction("RegexSplitAction", func() core.NodeAction { return &RegexSplitAction{} })
	core.RegisterNodeAction("RunProcessAction", func() core.NodeAction { return &RunProcessAction{} })
	core.RegisterNodeAction("SaveFileAction", func() core.NodeAction { return &SaveFileAction{} })
	core.RegisterNodeAction("ScatterPlotAction", func() core.NodeAction { return &ScatterPlotAction{} })
	core.RegisterNodeAction("SelectColumnsAction", func() core.NodeAction { return &SelectColumnsAction{} })
	core.RegisterNodeAction("SortAction", func() core.NodeAction { return &SortAction{} })
	core.RegisterNodeAction("SplitTextAction", func() core.NodeAction { return &SplitTextAction{} })
	core.RegisterNodeAction("TransposeAction", func() core.NodeAction { return &TransposeAction{} })
	core.RegisterNodeAction("TrimSpacesAction", func() core.NodeAction { return &TrimSpacesAction{} })
	core.RegisterNodeAction("ValueAction", func() core.NodeAction { return &ValueAction{} })
	core.RegisterNodeAction("WaitForClickAction", func() core.NodeAction { return &WaitForClickAction{} })
	core.RegisterNodeAction("XmlQueryAction", func() core.NodeAction { return &XmlQueryAction{} })
}

func (a *AddColumnAction) Tag() string {
	return "AddColumnAction"
}
func (a *AggregateAction) Tag() string {
	return "AggregateAction"
}
func (a *BarChartAction) Tag() string {
	return "BarChartAction"
}
func (a *CaseConvertAction) Tag() string {
	return "CaseConvertAction"
}
func (a *ConcatTablesAction) Tag() string {
	return "ConcatTablesAction"
}
func (a *ConvertAction) Tag() string {
	return "ConvertAction"
}
func (a *CopyFileAction) Tag() string {
	return "CopyFileAction"
}
func (a *DeleteFileAction) Tag() string {
	return "DeleteFileAction"
}
func (a *ExtractColumnAction) Tag() string {
	return "ExtractColumnAction"
}
func (a *FilterEmptyAction) Tag() string {
	return "FilterEmptyAction"
}
func (a *FormatStringAction) Tag() string {
	return "FormatStringAction"
}
func (a *FormulaAction) Tag() string {
	return "FormulaAction"
}
func (a *GateAction) Tag() string {
	return "GateAction"
}
func (a *GetMousePositionAction) Tag() string {
	return "GetMousePositionAction"
}
func (a *GetVariableAction) Tag() string {
	return "GetVariableAction"
}
func (a *GraphInputAction) Tag() string {
	return "GraphInputAction"
}
func (a *GraphOutputAction) Tag() string {
	return "GraphOutputAction"
}
func (a *HTTPRequestAction) Tag() string {
	return "HTTPRequestAction"
}
func (a *IfElseAction) Tag() string {
	return "IfElseAction"
}
func (a *JoinTextAction) Tag() string {
	return "JoinTextAction"
}
func (a *JsonQueryAction) Tag() string {
	return "JsonQueryAction"
}
func (a *LineChartAction) Tag() string {
	return "LineChartAction"
}
func (a *LinesAction) Tag() string {
	return "LinesAction"
}
func (a *ListFilesAction) Tag() string {
	return "ListFilesAction"
}
func (a *LoadFileAction) Tag() string {
	return "LoadFileAction"
}
func (a *MakeDirAction) Tag() string {
	return "MakeDirAction"
}
func (a *MapAction) Tag() string {
	return "MapAction"
}
func (a *MergeAction) Tag() string {
	return "MergeAction"
}
func (a *MinifyHTMLAction) Tag() string {
	return "MinifyHTMLAction"
}
func (a *MoveFileAction) Tag() string {
	return "MoveFileAction"
}
func (a *ParseTimeAction) Tag() string {
	return "ParseTimeAction"
}
func (a *PromptUserAction) Tag() string {
	return "PromptUserAction"
}
func (a *RegexFindAllAction) Tag() string {
	return "RegexFindAllAction"
}
func (a *RegexMatchAction) Tag() string {
	return "RegexMatchAction"
}
func (a *RegexReplaceAction) Tag() string {
	return "RegexReplaceAction"
}
func (a *RegexSplitAction) Tag() string {
	return "RegexSplitAction"
}
func (a *RunProcessAction) Tag() string {
	return "RunProcessAction"
}
func (a *SaveFileAction) Tag() string {
	return "SaveFileAction"
}
func (a *ScatterPlotAction) Tag() string {
	return "ScatterPlotAction"
}
func (a *SelectColumnsAction) Tag() string {
	return "SelectColumnsAction"
}
func (a *SortAction) Tag() string {
	return "SortAction"
}
func (a *SplitTextAction) Tag() string {
	return "SplitTextAction"
}
func (a *TransposeAction) Tag() string {
	return "TransposeAction"
}
func (a *TrimSpacesAction) Tag() string {
	return "TrimSpacesAction"
}
func (a *ValueAction) Tag() string {
	return "ValueAction"
}
func (a *WaitForClickAction) Tag() string {
	return "WaitForClickAction"
}
func (a *XmlQueryAction) Tag() string {
	return "XmlQueryAction"
}
